----- Begin Fatal Exception 12-Nov-2024 16:38:16 KST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing the python configuration file named conf.py
Exception Message:
A std::exception was thrown.
File "conf.py" could not be opened!
----- End Fatal Exception -------------------------------------------------
