DEBUG 2024-11-06 06:48:29.970 UTC: 	 CRAB Client version: v3.240930
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Running on: Linux lxplus929.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Not using Singularity
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-06 06:48:29.970 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-06 06:48:29.972 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-06 06:48:29.972 UTC: 	 Loading CRAB configuration file.
ERROR 2024-11-06 06:48:29.994 UTC: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab_conf.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-11-06 06:48:29.994 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 342, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py", line 16
    config.Data.inputDataset = '/Muon/Run2022C-27Jun2023-v1/AOD
                                                               ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 57, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 350, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py
Due to error:
EOL while scanning string literal (crab_conf.py, line 16)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/WMCore/Configuration.py", line 342, in loadConfigurationFile
    modRef = imp.load_module(cfgBaseName, modPath[0],
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/el9_amd64_gcc12/external/python3/3.9.14-8e02587b42992e07ed46b00eca9dfc3a/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_conf.py", line 16
    config.Data.inputDataset = '/Muon/Run2022C-27Jun2023-v1/AOD
                                                               ^
SyntaxError: EOL while scanning string literal


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240930.00/lib/CRABClient/Commands/SubCommand.py", line 91, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab_conf.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-11-06 06:48:30.000 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-07 07:53:36.550 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Running on: Linux lxplus9107.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Not using Singularity
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Executing command: 'kill'
DEBUG 2024-11-07 07:53:36.550 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-07 11:59:41.763 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Not using Singularity
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-07 11:59:41.764 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-07 11:59:41.766 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-07 11:59:41.766 UTC: 	 Loading CRAB configuration file.
ERROR 2024-11-07 11:59:41.809 UTC: 	 Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-11-07 11:59:41.809 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 96, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: In case of Automatic splitting, the Data.unitsPerJob parameter must be in the [180, 2700] minutes range. You asked for 100 minutes.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-11-07 11:59:41.816 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-07 13:24:13.914 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Not using Singularity
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Executing command: 'status'
DEBUG 2024-11-07 13:24:13.914 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-07 13:24:13.918 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2022F is not a valid CRAB project directory.
ERROR 2024-11-07 13:24:13.918 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2022F is not a valid CRAB project directory.
INFO 2024-11-07 13:24:13.922 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-08 14:34:42.795 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Running on: Linux lxplus950.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Not using Singularity
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-08 14:34:42.795 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-08 14:34:42.796 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-08 14:34:42.838 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-08 14:34:42.838 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-08 14:34:43.013 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-08 14:34:43.017 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2022C' already exists 
Please change the requestName in the config file
ERROR 2024-11-08 14:34:43.017 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2022C' already exists 
Please change the requestName in the config file
INFO 2024-11-08 14:34:43.022 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 08:39:57.206 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Not using Singularity
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-09 08:39:57.206 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-09 08:39:57.207 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-09 08:39:57.207 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-09 08:39:57.236 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-09 08:39:57.236 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023C0' already exists 
Please change the requestName in the config file
ERROR 2024-11-09 08:39:57.236 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023C0' already exists 
Please change the requestName in the config file
INFO 2024-11-09 08:39:57.240 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 08:40:29.521 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 08:40:29.521 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Not using Singularity
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-09 08:40:29.522 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-09 08:40:29.524 UTC: 	 Will use CRAB configuration file crab_conf.py
DEBUG 2024-11-09 08:40:29.524 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-09 08:40:29.575 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-09 08:40:29.575 UTC: 	 Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023B0' already exists 
Please change the requestName in the config file
ERROR 2024-11-09 08:40:29.575 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab_projects/crab_MuonSkimming_Run2023B0' already exists 
Please change the requestName in the config file
INFO 2024-11-09 08:40:29.580 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 13:10:14.679 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Not using Singularity
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Executing command: 'status'
DEBUG 2024-11-09 13:10:14.679 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-09 13:10:14.681 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
ERROR 2024-11-09 13:10:14.681 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
INFO 2024-11-09 13:10:14.685 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-09 13:10:18.471 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Not using Singularity
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Executing command: 'status'
DEBUG 2024-11-09 13:10:18.471 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-09 13:10:18.472 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
ERROR 2024-11-09 13:10:18.472 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023V0 is not a valid CRAB project directory.
INFO 2024-11-09 13:10:18.475 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-10 07:19:22.786 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Running on: Linux lxplus936.cern.ch 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 18 14:35:40 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Not using Singularity
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Executing command: 'status'
DEBUG 2024-11-10 07:19:22.786 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-10 07:19:22.787 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023C1/ is not a valid CRAB project directory.
ERROR 2024-11-10 07:19:22.787 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023C1/ is not a valid CRAB project directory.
INFO 2024-11-10 07:19:22.789 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-12 03:15:59.815 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Running on: Linux lxplus962.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Not using Singularity
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 03:15:59.815 UTC: 	 Executing command: 'status'
DEBUG 2024-11-12 03:15:59.816 UTC: 	 Could not find CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3; creating a new one.
ERROR 2024-11-12 03:15:59.819 UTC: 	 Unhandled Exception!
ERROR 2024-11-12 03:15:59.819 UTC: 	 [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 268, in __init__
    self.crab3dic = self.getConfiDict()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 570, in getConfiDict
    with open(crabCacheFileName_tmp, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
ERROR 2024-11-12 03:15:59.820 UTC: 	 ERROR: PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.55522'
ERROR 2024-11-12 03:15:59.821 UTC: 	 
	Please email cmstalk+computing-tools@dovecotmta.cern.ch for support with the crab.log file or crab.log URL.
ERROR 2024-11-12 03:15:59.821 UTC: 	 	Client Version: v3.241030
ERROR 2024-11-12 03:15:59.821 UTC: 	 	Please use 'crab uploadlog' to upload the log file /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log to the CRAB cache.
DEBUG 2024-11-12 03:28:58.750 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Running on: Linux lxplus962.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Not using Singularity
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 03:28:58.750 UTC: 	 Executing command: 'status'
DEBUG 2024-11-12 03:28:58.752 UTC: 	 Could not find CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3; creating a new one.
ERROR 2024-11-12 03:28:58.755 UTC: 	 Unhandled Exception!
ERROR 2024-11-12 03:28:58.755 UTC: 	 [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 268, in __init__
    self.crab3dic = self.getConfiDict()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 570, in getConfiDict
    with open(crabCacheFileName_tmp, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
ERROR 2024-11-12 03:28:58.756 UTC: 	 ERROR: PermissionError: [Errno 13] Permission denied: '/afs/cern.ch/user/w/wkwon/.crab3.66291'
ERROR 2024-11-12 03:28:58.756 UTC: 	 
	Please email cmstalk+computing-tools@dovecotmta.cern.ch for support with the crab.log file or crab.log URL.
ERROR 2024-11-12 03:28:58.757 UTC: 	 	Client Version: v3.241030
ERROR 2024-11-12 03:28:58.757 UTC: 	 	Please use 'crab uploadlog' to upload the log file /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log to the CRAB cache.
DEBUG 2024-11-12 04:17:12.021 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Running on: Linux lxplus9121.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Not using Singularity
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-11-12 04:17:12.022 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-17 07:07:32.003 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Executing command: 'status'
DEBUG 2024-11-17 07:07:32.003 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
ERROR 2024-11-17 07:07:32.004 UTC: 	 Error: crab_projects/crab_MuonSkimming_Run2023CC/ is not a valid CRAB project directory.
ERROR 2024-11-17 07:07:32.004 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 285, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 690, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_MuonSkimming_Run2023CC/ is not a valid CRAB project directory.
INFO 2024-11-17 07:07:32.006 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-17 07:14:38.995 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-11-17 07:14:38.995 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
DEBUG 2024-11-17 07:27:10.208 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Not using Singularity
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Executing command: 'submit'
DEBUG 2024-11-17 07:27:10.208 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
INFO 2024-11-17 07:27:10.209 UTC: 	 Will use CRAB configuration file crab_conf_file.py
DEBUG 2024-11-17 07:27:10.209 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-11-17 07:27:10.260 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-11-17 07:27:10.260 UTC: 	 Error: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
ERROR 2024-11-17 07:27:10.260 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/Commands/SubCommand.py", line 332, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 386, in createWorkArea
    requestName = getRequestName(requestName)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241030.00/lib/CRABClient/ClientUtilities.py", line 364, in getRequestName
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: The '/' character is not accepted in the requestName parameter. If your intention was to specify the location of your task, please use the General.workArea parameter.
INFO 2024-11-17 07:27:10.264 UTC: 	 Log file is /eos/home-w/wkwon/CMSSW_14_0_12/src/work/skim/crab.log
DEBUG 2024-11-17 08:25:20.117 UTC: 	 CRAB Client version: v3.241030
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Running on: Linux lxplus9122.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Not using Singularity
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Operating System: Red Hat Enterprise Linux 9.4 (Plow)
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Executing command: 'getlog'
DEBUG 2024-11-17 08:25:20.117 UTC: 	 Found CRAB cache file /afs/cern.ch/user/w/wkwon/.crab3
